### ISSUE TITLE
Gmavenplus support for targetBytecode 14

### ISSUE THREAD

**Issue by silviugabor** [groovy/GMavenPlus#152]
Current gmavenplus targetBytecode  property validation within the compile MOJO component does not allow configuring Groovy compiler for targetBytecode > 13.

**Comment by keeganwitt** [comment]
Thanks for the reminder, I'd missed this update.

I'm also going to add a new flag to let you disable the version compatibility check, so that way you don't have to wait for me to update the plugin in the future, (you can keep your eye on [CompilerConfiguration.java](https://github.com/apache/groovy/blob/master/src/main/java/org/codehaus/groovy/control/CompilerConfiguration.java) for when support gets added to Groovy).

**Comment by silviugabor** [comment]
I appreciate your quick response and I think that your idea to let the user bypass the bytecode validation for groovy is great, as it enables any future bytecode version support to depend on Groovy's compiler configuration checks alone.

**Comment by keeganwitt** [comment]
Yea, I dunno why I didn't think of it before, these version numbers come out so fast now. I've worried about the ability of the whole ecosystem (ASM and all the projects that use it, like Groovy, Kotlin, etc) to keep up. Some aren't trying, like Kotlin is still 1.6 or 1.8.  I don't understand why Oracle is doing this (or why Sun did it before them).  As far as I know, the class file format doesn't change every release, and in fact, it usually doesn't.
