### ISSUE TITLE
Any chance to publish 1.10.2-SNAPSHOT artifacts to OSS Sonatype?

### ISSUE THREAD

**Issue by ilgrosso** [groovy/GMavenPlus#176]
It would be nice to check the latest fixes made.

**Comment by keeganwitt** [comment]
I was actually hoping to publish the non-snapshot fairly shortly, but am thinking again this morning, given that there's some flux with https://issues.sonatype.org/browse/OSSRH-61019.  I pushed it to the Sonatype repo (https://oss.sonatype.org/content/repositories/snapshots).

To workaround that issue, you can add this
```xml
  <pluginRepositories>
    <pluginRepository>
      <id>groovy jcenter</id>
      <url>https://dl.bintray.com/groovy/maven/</url>
    </pluginRepository>
  </pluginRepositories>
  <repositories>
    <repository>
      <id>groovy jcenter</id>
      <url>https://dl.bintray.com/groovy/maven/</url>
    </repository>
  </repositories>
```

The `pluginRepositories` part isn't needed if you are using the default `includeClasspath`.

**Comment by keeganwitt** [comment]
Actually, even if the coordinates change is reversed, that won't affect the package changes, so that's not really a reason to hold up the release.  It only really affects my internal test re-tooling.  I keep forgetting that fix I added for Groovy in uber jars years ago negates the need for the plugin to be aware of Groovy's Maven coordinates.

I'll probably do a release in the next couple days, unless I find some issue (so far testing has gone smoothly).  Please do let me know if you find any issues.

**Comment by ilgrosso** [comment]
1.10.2-SNAPSHOT works fine with JDK 16ea: https://travis-ci.com/github/ilgrosso/syncope/jobs/396234509#L387-L389
Nice job :+1: 

Now I think I'll have to wait for Mockito to work with JDK 16ea: https://travis-ci.com/github/ilgrosso/syncope/jobs/396234509#L2867-L2905

**Comment by keeganwitt** [comment]
Thanks for the feedback!
