### ISSUE TITLE
GMavenPlus plugin is throwing NullPointerException for running Spock test cases.

### ISSUE THREAD

**Issue by deepakmehra10** [groovy/GMavenPlus#180]
GMavenPlus plugin configuration

`<plugin>
        <groupId>org.codehaus.gmavenplus</groupId>
        <artifactId>gmavenplus-plugin</artifactId>
        <version>${gmavenplus-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <sources>
            <fileset>
              <directory>${project.basedir}/src/test/groovy</directory>
              <includes>
                <include>**/*.groovy</include>
              </includes>
            </fileset>
          </sources>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.4</version>
            <scope>runtime</scope>
          </dependency>
        </dependencies>
      </plugin>`
From **mvn test** logs

[ERROR] Unable to determine Groovy version.  Is Groovy declared as a dependency?

**Comment by keeganwitt** [comment]
Have you looked at the Spock examples?
Spock 1: https://github.com/groovy/GMavenPlus/wiki/Examples#spock-1-and-junit
Spock 2: https://github.com/groovy/GMavenPlus/wiki/Examples#spock-2-and-junit

The compilation goal by default expects Groovy to be in your project's dependencies, not the plugin dependencies. I think that default is appropriate for most use cases, but if you have some reason that you can't have Groovy in the project's test dependencies, you can also change [includeClasspath](http://groovy.github.io/GMavenPlus/compileTests-mojo.html#includeClasspath) to `PROJECT_AND_PLUGIN` or `PLUGIN_ONLY`.

**Comment by deepakmehra10** [comment]
In one of your examples I could see that you asked to include dependencies in plugin for a reason, if that's not correct, please let me know.

Above solved the issue but now it's not recognizing the Specification class.
unable to resolve class spock.lang.Specification

**Comment by keeganwitt** [comment]
So, I had some goals which include the plugin classpath for ease of use (like the execute mojo). I received a few requests to make it more flexible which classpath is used for other goals, so I added the `includeClasspath` parameter. At least some of the use cases requesting this I felt like were not good practice, but this plugin is built with the philosophy that it's your foot to shoot if you wish, so it's now there if needed.  I would say in your typical compilation usage, that's not something you'd normally do, and not something I recommend, since other things won't work with that (for example, Eclipse or IntelliJ won't give you autocompletion because it won't see it as a dependency if it's only a plugin depedency).

What do you mean "above"? If you specified `PLUGIN_ONLY`, then you'd also need to add Spock dependencies to the plugin dependencies. If you specified `PROJECT_AND_PLUGIN` Spock dependencies must be in either the project or the plugin dependencies. If you specified `PROJECT_ONLY` (or nothing, since that's the default for this mojo), Spock dependencies must be in project dependencies.

**Comment by deepakmehra10** [comment]
I tried it a different way, we don't have to use groovy dependency if we are not using it. Please close the issue. Thank you for the quick reply. Appreciate your help @keeganwitt
