### ISSUE TITLE
Groovy class loaders are not independent between modules

### ISSUE THREAD

**Issue by TobiX** [groovy/GMavenPlus#183]
I'm currently not sure if this is a bug or just a "This is how Java works, deal with it" problem, so feel free to close this if this "works as intended".

When running scripts in multiple independent maven modules under the same parent, the class loaders are not independent. I have attached a ZIP with a minimal reproducer ([gmavenplus-test.zip](https://github.com/groovy/GMavenPlus/files/5653680/gmavenplus-test.zip)):

```
parent
├── a
└── b
```

- `a` has a dependency on log4j
- `b` has a dependency on junit

All modules run a script which simply does `Class.forName()` for both, a class from log4j and a class from junit. The result is what you expect for whatever module runs first, but classes are found from both modules in whichever module is run last.

This surprised me a bit.  I was under the impression that the "temporary" class loader which this plugin uses is destroyed after each run (or at least after each maven module)

**Comment by keeganwitt** [comment]
I haven't seen the behavior explicitly documented.  This is all I could find: http://takari.io/book/91-maven-classloading.html.  I'm doing some experiments to understand better.
I thought the way it worked was that each goal had it's own classpath (though I'm not sure what it did for submodules).  But possibly I was mistaken and it's an artifact of the parent classloader I was choosing.

**Comment by keeganwitt** [comment]
By the way, this doesn't happen when using `includeClasspath` of `PROJECT_ONLY`. This does require you to have the dependency in the project, instead of in the plugin, but it is a clue as to what's going on.

At the moment, I believe the parent classloader is the classloader from the Plexus ClassRealm.  It appears this parent is reused for both goal executions, and that's why it seems to be additive (whichever one runs second has both depedencies), even if I create another classloader within the mojo's `execute()`.  Still experimenting...

**Comment by TobiX** [comment]
Thank you very much for the fix 👍🏽 I'll probably be able to test it after the holidays.

**Comment by keeganwitt** [comment]
Thanks for reporting this (and for providing the test case)!  I just made a release with this fix (1.12.0).
