### ISSUE TITLE
Help with GMavenPlus / MavenSimpleLogger problems

### ISSUE THREAD

**Issue by nathanmarz** [groovy/GMavenPlus#214]
I'm having trouble turning off logging when using mvn gplus:shell. I don't have any logging xml or properties files on the classpath, and when checking the class of `org.slf4j.LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME)` I discovered `MavenSimpleLogger` was configured. It appears this is what's printing the log messages. Is GMavenPlus configuring this? Is there a way to turn it off?

**Comment by nathanmarz** [comment]
I also found that providing a log4j2.properties file on the classpath does not change this behavior, even after confirming with `-Dlog4j2.debug` that log4j was picking up the configuration file.

**Comment by nathanmarz** [comment]
I discovered running the shell with `mvn gplus:shell -Dorg.slf4j.simpleLogger.defaultLogLevel=ERROR` fixes the problem. Is there a way to configure the pom.xml to automatically include that config when running just `mvn gplus:shell`?

**Comment by keeganwitt** [comment]
The shell mojo by default includes both your project's test classpath and the classpath of GMavenPlus itself, so that you can easily add dependencies to the plugin to use in your scripts or as a test. That's probably why `MavenSimpleLogger` is on the classpath. You can control this with [`includeClasspath`](http://groovy.github.io/GMavenPlus/shell-mojo.html#includeClasspath).

I don't know of a way to specify default Java arguments to a plugin invocation because those are passed into java itself and merely passed along into anything invoked in that jvm instance.
