### ISSUE TITLE
Call another plugin goal execution from a groovy script

### ISSUE THREAD

**Issue by mstevens83** [groovy/GMavenPlus#48]
Hi,

Would it be possible to add a feature which would allow calling the execution of a goal of another maven plugin from within a groovy script being executed by GMavenPlus?

For example it could look like this:
```
<script><![CDATA[
	if(somecontion)
		project.call('resources:resources');
]]></script>
```

**Comment by keeganwitt** [comment]
I couldn't really mix in new methods onto Maven's API as you show because I'm using Java, not Groovy.  Hence probably the best way for you to do this would be to use the bindings GMavenPlus already has to setup your own invocation.  I'm not sure yet, the best way to do that.  So far I haven't seen anyone recommend a way that doesn't fork the lifecycle.  I'm not sure convoluting the lifecycle as you suggest is a good idea, but it's your foot to shoot.

Maybe something [like this](http://stackoverflow.com/a/11529296) would work?
