### ISSUE TITLE
File with unknown license

### ISSUE THREAD

**Issue by puntogil** [groovy/GMavenPlus#50]
The following source files are without license headers.
GMavenPlus-1.5/src/main/java/org/codehaus/gmavenplus/plexus/AbstractIncludeProjectDependenciesComponentConfigurator.java
Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
Thanks in advance
Regards

**Comment by keeganwitt** [comment]
I originally had borrowed a few lines from from this StackOverflow [answer](http://stackoverflow.com/a/2659324/160256), but the code has been changed a fair amount from the original.  I'm no licensing expert, but I'm thinking what was used is fair use and so it's Apache also, but let me think about it some more.  Worst case scenario, it'd be Creative Commons SA, since that's what StackOverflow content is contributed under, which I believe can still be used in Apache projects.

**Comment by keeganwitt** [comment]
I marked the file as being Apache.  Thanks for the question.  If you have any other questions/concerns, feel free to reach out on our [mailing list](https://groups.google.com/d/forum/gmavenplus).
