### ISSUE TITLE
Default value for testStubsOutputDirectory parameter is incorrect

### ISSUE THREAD

**Issue by kovayur** [groovy/GMavenPlus#58]
Intellij IDEA 2016.1.3 fails to compile the module with the following setup:
-  Some unit tests are written on groovy
-  gmavenplus plugin 1.5 with testGenerateStubs goal
-  junit dependency with _test_ scope

As a result: compilation failure with unavailability to find junit classes.

In org.codehaus.gmavenplus.mojo.AbstractGroovyStubSourcesMojo.java:

``` java
    /**
     * The location for the compiled test classes.
     *
     * @parameter default-value="${project.build.directory}/generated-sources/groovy-stubs/test"
     */
    protected File testStubsOutputDirectory;
```

I think the problem is that IDEA considers everything in generated-sources folder as main sources and this looks correct.

When I set _testStubsOutputDirectory_ to:

``` xml
<configuration>
    <testStubsOutputDirectory>
        ${project.build.directory}/generated-test-sources/groovy-stubs/test
     </testStubsOutputDirectory>
</configuration>
```

It works fine

**Comment by keeganwitt** [comment]
This was set as the default as a carry-over of GMaven [behavior](https://github.com/groovy/gmaven/blob/master/gmaven-plugin/src/main/java/org/codehaus/gmaven/plugin/stubgen/GenerateTestStubsMojo.java). I feel like changing this is kinda side-stepping the issue for a subset of the overall problem. If IntelliJ is adding groovy-stubs as a source dir, then if you generated stubs for main Groovy sources, you'd end up with duplicate classes in your source. I'd rather raise an issue with IntelliJ telling them to ignore that directory. Make sense?

**Comment by zman0900** [comment]
I found a work-around for this.  IntelliJ always re-adds the stubs as generated source directories each time a `mvn clean` is ran externally, no matter how much I mark them as ignored.  I set the stubs directories to be completely outside of the project's directory tree so IntelliJ never has a chance to see them.  Build/test still seems fine both directly through maven and within IntelliJ.

```xml
<stubsOutputDirectory>${java.io.tmpdir}/${project.groupId}.${project.artifactId}/stubs</stubsOutputDirectory>
<testStubsOutputDirectory>${java.io.tmpdir}/${project.groupId}.${project.artifactId}/test-stubs</testStubsOutputDirectory>
```

**Comment by keeganwitt** [comment]
@zman0900 I think that could cause issues with joint compilation, as javac won't be able to find the stubs.  javac doesn't look in java.io.tmpdir for sources to compile, right?

**Comment by zman0900** [comment]
I was getting the same error as the OP, where junit classes could not be found, which turned out to be because intellij was including the stubs as source directories, leading to duplicate classes.  Marking those directories as ignored would temporarily fix the problem, but they would often become un-ignored.  

Setting the stubs dirs to be in the tmp directory seems to be working so far.  This is a maven module with both java and groovy sources.  Compilation works and all tests still pass, both from within intellij and when run from command line maven.  

I assume the stubs are still being compiled.  I see some class files under target/classes and target/test-classes that have the same names as my groovy classes. Also I have a few java unit tests that call java code which itself calls groovy code, and I think that would fail if stubs were not compiled.  I completely cleaned out the target directories, so these aren't left over from before.

Here's my full config for relevant plugins (groovy is v2.4.7):

```xml
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.5</version>
                <configuration>
                    <stubsOutputDirectory>${java.io.tmpdir}/${project.groupId}.${project.artifactId}/stubs</stubsOutputDirectory>
                    <testStubsOutputDirectory>${java.io.tmpdir}/${project.groupId}.${project.artifactId}/test-stubs</testStubsOutputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>groovy-compile</id>
                        <goals>
                            <goal>addSources</goal>
                            <goal>addTestSources</goal>
                            <goal>generateStubs</goal>
                            <goal>compile</goal>
                            <goal>testGenerateStubs</goal>
                            <goal>testCompile</goal>
                            <goal>removeStubs</goal>
                            <goal>removeTestStubs</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.6.0</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.12</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/main/groovy</source>
                            </sources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>add-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src/test/groovy</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by zman0900** [comment]
To add on to this, I've been using the above config for a few days now, and I did run into one small problem.  The stubs in the tmp dir are not cleaned up, so stale files can get left over as you add/remove/rename classes.  I solved this by setting the clean plugin to remove the directory:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>${java.io.tmpdir}/${project.groupId}.${project.artifactId}</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
```

**Comment by keeganwitt** [comment]
Are you guys using the [GMavenPlus plugin](https://plugins.jetbrains.com/plugin/7442-gmavenplus-intellij-plugin) in IntellliJ?

**Comment by zman0900** [comment]
I have never used that plugin.  IntelliJ does still automatically detect both the java and groovy source and test source directories without it.

**Comment by keeganwitt** [comment]
Actually IntelliJ will exclude the stub directories if the goals are named `generateStubs` and `generateTestStubs` and the stub directory is named `outputDirectory`.  Since I have the fields named `stubsOutputDirectory` and `testStubsOutputDirectory` and the goal is named `testGenerateStubs` instead of `generateTestStubs` (something I wanted to rename anyway, but avoided doing to avoid breaking changes -- see #31).

In the mean time, you can add it to a place IntellIj does exclude
```xml
<configuration>
    <stubsOutputDirectory>${project.build.directory}/generated-sources/groovy-stubs</stubsOutputDirectory>
    <testStubsOutputDirectory>${project.build.directory}/generated-sources/groovy-stubs</testStubsOutputDirectory>
</configuration>
```
This will cause Java to compile against all your Groovy, test and main, which could cause conflicts though.

Now that I see what's going on this should be a simple fix, but it'll unfortunately be a breaking change.

**Comment by zman0900** [comment]
After upgrading to 1.6 and removing the stubsOutputDirectory and testStubsOutputDirectory configs, I still get intellij detecting the stubs directories as both "sources root" and "generated sources root".  These directories are showing up in `target/generated-sources/groovy-stubs/{main,test}`.

Strangely, using the same work-around of writing them to the tmpdir as I did before still works fine.  The stubs are still written in `target/generated-sources/groovy-stubs/{main,test}` instead of the tmpdir, but IntelliJ doesn't detect them as sources of any kind.

**Comment by zman0900** [comment]
Scratch that, after some further use compiling in a terminal a few times, the stubs have shown back up an unwanted sources in IntelliJ, even with the output set to be in tmpdir.

**Comment by keeganwitt** [comment]
Did you reimport the project in IntelliJ?  This seemed to work in the tests I did before shipping 1.6.

**Comment by zman0900** [comment]
I ran the maven "reimport" option a couple times within IntelliJ, but I did not completely create a new project if that's what you mean.

**Comment by keeganwitt** [comment]
Ok.  So when I tested I had the [GMavenPlus IntelliJ plugin](https://plugins.jetbrains.com/plugin/7442-gmavenplus-intellij-plugin) installed.  It's this that hooks into IntelliJ to tell it to ignore those directories.

**Comment by olmedosilvana** [comment]
@keeganwitt this issue still persists with Intellij IDEA 2018.2 and gmavenplus-plugin 1.6, can it be open again? Thanks in advance

**Comment by keeganwitt** [comment]
@olmedosilvana are you using the GMavenPlus IntelliJ plugin?

**Comment by albers** [comment]
Installing the GMavenPlus IntelliJ plugin resolved the issue for me. The generated Groovy stubs are now ignored by the IDE.

IntelliJ 2018.3.3, Maven 3.6.0, gmavenplus-plugin 1.6, Groovy 2.5.5, Java 11.

**Comment by maxime-hochet** [comment]
I get the same error (class XXX already exists in IntelliJ) with this setup:

**IntelliJ**
- IntelliJ: 2019.1
- GMavenPlugin: 2.0
- Java: 8 (Hum... I had to downgrade: new mission)

**Project**
- Maven: 3.6.3
- GMavenPlus: 1.6.3
- Groovy: 2.5.6
