### ISSUE TITLE
gmaven ignores locally defined dependency on groovy-all

### ISSUE THREAD

**Issue by reckart** [groovy/GMavenPlus#64]
I would like to use the groovydoc target, but it does not seem to work unless I add a dependency on groovy-all to the dependency section of the POM.

Here the error:

```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.5:groovydoc (default-cli) on project dkpro-script-groovy: Unable to get a Groovy class from classpath.  Do you have Groovy as a compile dependency in your project?: org.codehaus.groovy.tools.groovydoc.GroovyDocTool -> [Help 1]
```

IMHO adding groovy-all as a dependency locally to the plugin should suffice. I don't really want to have a dependency on groovy-all in my project. I prefer depending on specific groovy modules like groovy, groovy-templates, and groovy-json.

```
  <profiles>
    <profile>
      <id>groovy</id>
      <activation>
        <file>
          <exists>src/main/groovy</exists>
        </file>
      </activation>
      <dependencies>
        <dependency>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy</artifactId>
        </dependency>
        <dependency>
          <!-- This should not be necessary -->
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy-all</artifactId>
          <version>${groovy.version}</version>
        </dependency>
        <dependency>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy-templates</artifactId>
        </dependency>
      </dependencies>
      <build>
        <plugins>
          <plugin>
            <groupId>org.codehaus.gmavenplus</groupId>
            <artifactId>gmavenplus-plugin</artifactId>
            <version>1.5</version>
            <executions>
              <execution>
                <goals>
                  <goal>addSources</goal>
                  <goal>addTestSources</goal>
                  <goal>generateStubs</goal>
                  <goal>compile</goal>
                  <goal>testGenerateStubs</goal>
                  <goal>testCompile</goal>
                  <goal>groovydoc</goal>
                  <goal>testGroovydoc</goal>
                  <goal>removeStubs</goal>
                  <goal>removeTestStubs</goal>
                </goals>
              </execution>
            </executions>
            <dependencies>
              <dependency>
                <!-- This should suffice -->
                <groupId>org.codehaus.groovy</groupId>
                <artifactId>groovy-all</artifactId>
                <version>${groovy.version}</version>
              </dependency>
            </dependencies>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
```

**Comment by keeganwitt** [comment]
GMavenPlus has to build a classpath of the project's source and dependencies and invoke Groovy classes against that.  I intentionally didn't include the plugin's classpath because I didn't want to pollute the compilation classpath with classes from the plugin.  I do include the plugin's classpath the tools mojos (like groovyConsole, and groovyShell) for convenience, but I don't include the plugin classpath for compilation, stub generation, or groovydoc mojos.  I don't think it'd be safe to include the plugin classplath in the compilation or stub generation mojos, but maybe it'd be safe for groovydoc -- let me look into it.

**Comment by keeganwitt** [comment]
One thing I forgot to mention is that you can depend on just the jars you need, but will need to depend on the groovy-groovydoc dependency for the groovydoc generation.

**Comment by keeganwitt** [comment]
Sorry for the long silence.  I think given the GroovyDoc classes are still doing parsing and AST processing, there is a chance merging the classpaths could cause issues (though not a huge chance since GMavenPlus doesn't have a lot on it's classpath).  I guess the way to deal with this is add a flag to control classpath behavior and let people do whatever they want.
