### ISSUE TITLE
Custom groovydoc doclet

### ISSUE THREAD

**Issue by dee-kryvenko** [groovy/GMavenPlus#91]
As far as I can see `org.codehaus.groovy.tools.groovydoc.GroovyDocTool` is hardcoded. Is there a reason or a pitfalls to not to have it parametrized?

**Comment by keeganwitt** [comment]
All class names are hard-coded.  The only reason it's a string instead of a direct call to an object is that I used reflection so that the plugin could work with multiple versions of Groovy.

I probably could make it configurable.  Why would you want to though?  You forked the Groovydoc generation code?

**Comment by llibicpep** [comment]
@keeganwitt I am looking for a way to create custom doclet as I would normally do it in JavaDoc. Now I see the things are much different in groovy due to initial ant focused implementation, but GroovyDocTool seems to be the most close candidate to be used as an extension point. What I am currently do is writing my own implementation of that class without real inheritance (basically I rely on the methods gmavenplus call via reflection), and of course I don't like it but this is the best or actually the only one possible way I found so far. If you have a better ideas I'm all ears.

**Comment by keeganwitt** [comment]
Sorry, I meant to circle back to this.  If we were to parameterize the class names, what classes would you need?  All of these?
* org.codehaus.groovy.tools.groovydoc.GroovyDocTool
* org.codehaus.groovy.tools.groovydoc.OutputTool
* org.codehaus.groovy.tools.groovydoc.FileOutputTool
* org.codehaus.groovy.tools.groovydoc.ResourceManager
* org.codehaus.groovy.tools.groovydoc.ClasspathResourceManager

**Comment by llibicpep** [comment]
In my particular case I needed to customize `org.codehaus.groovy.tools.groovydoc.GroovyDocTool`. But I think it makes sense to give as much flexibility as it's possible without an extra hassle.

**Comment by keeganwitt** [comment]
I apologize again, I lost track of this.  Is this feature still of interest to you?  If so, to clarify, would it work to to provide templates used by these classes? Or do you really need to fork the Groovydoc classes?

**Comment by dee-kryvenko** [comment]
My use case is - I'm programmatically generating usage doc with maven for my tool based on code as part of my CI. It isn't exactly a Groovy API document as my tool uses DSL for the user input, so both logic and template is different for me. I need to be able to fork the class, or to be more explicit - it's a totally custom implementation that walks through a certain package and fetches comments from class fields with my special annotation.

**Comment by keeganwitt** [comment]
Okie dokie,that's what I thought. I just wanted to double check the change I recently added for custom templates wasn't sufficient. I'll add properties for custom classes once I'm back from vacation next week.
